name: ⚙️ Check App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  vitest:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
      
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Vitest
        run: pnpm test
        continue-on-error: false

  comment_pr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-20.04

    steps:
      - name: Comment PR
        if: ${{ github.actor != 'hadez8877' && github.actor != github.repository_owner }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hey @${{ github.actor }}! Thank you for your pull request.
            However, please do not open pull requests against `main`, as stated in
            [CONTRIBUTING](https://github.com/hadez8877/Wumpus#contributing):
            > [...] make a PR to the dev branch (hadez8877/Wumpus/dev)

            To change the base branch, edit this pull request and select the new base.
            To prevent conflicts, either `git merge upstream/dev` to your local branch, or
            rebase your local branch onto dev, like so: `git rebase upstream/dev`.
            Afterwards, (force) push your branch, and you're set!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}